# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41de985b3768ce801f6ddacd33d3a8c114850d6325d6e05784c29eea897e338495d08cc36a8806d370936f732b2cf0f4aa94f3c41dc058eefed94f18ddbd6af4

test:
  secret_key_base: 4b6524e097b55229d667ce5c40af2e2ae2f2926982371c0005d38f08e011e7b5d320a0ca9cc286e745ad8174190ed9fae44e4a0c5d430c46b1134878689a0aca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
